/* native/main.c -- NATIVE_PLAN.md N8 task 6 + N10 task 1: the loader.
 *
 * Everything a user types is parsed and dispatched by selfhost/cli.funny,
 * which is FunnyLang. This file does the three things that cannot be done
 * from inside the language before the language is running:
 *
 *   1. set up the console (UTF-8 + ANSI on Windows),
 *   2. read the two diagnostic flags, because they configure the *runtime's*
 *      own renderer and have to apply before any program runs,
 *   3. hand the embedded toolchain bundle argv.
 *
 * The bundle is compiled into this binary as a byte array
 * (native/toolchain_blob.c, generated by tools/bin2c.funny), so the shipped
 * artifact is one file: nothing to find, nothing to ship alongside, nothing
 * that can get out of step with the executable. FUNNY_CLI replaces it from a
 * file, which is the development loop.
 *
 * `--version` is answered here rather than in the bundle, deliberately: it is
 * the one command someone runs when an install looks broken, so it must not
 * depend on anything else working.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "diag.h"
#include "platform.h"
#include "runner.h"
#include "toolchain_blob.h"

/* Kept in step with selfhost/cli.funny's own VERSION/BYTECODE_VERSION by
   `tests/native/test_native_cli.py`, which reads both and compares them --
   two copies of a version string is exactly the kind of thing that drifts
   silently. */
#define FUNNY_VERSION "2.0.0"
#define FUNNY_BYTECODE_VERSION 2

static uint8_t *read_file(const char *path, size_t *outLen) {
    unsigned char *data;
    size_t len;
    char errbuf[256];
    if (!platform_read_file(path, &data, &len, errbuf, sizeof(errbuf))) return NULL;
    *outLen = len;
    return (uint8_t *)data;
}

/* FUNNY_CLI replaces the embedded toolchain with one from a file. This is
   the iteration loop: edit selfhost/, relink the bundle, point at it, without
   regenerating the blob and recompiling C in between. Deliberately *not* a
   search of the filesystem -- a shipped binary's behaviour should not depend
   on what happens to be sitting next to it. */
static uint8_t *load_cli_override(size_t *outLen) {
    const char *override = getenv("FUNNY_CLI");
    if (override == NULL || override[0] == '\0') return NULL;
    uint8_t *data = read_file(override, outLen);
    if (data == NULL) {
        fprintf(stderr, "FUNNY_CLI is set to '%s', which couldn't be read.\n", override);
        exit(1);
    }
    return data;
}

int main(int argc, char **argv) {
    platform_console_init(); /* UTF-8 + ANSI on Windows; a no-op elsewhere */

    /* The two flags that configure the runtime's own diagnostic renderer are
       read here and installed process-wide, so every nested run -- the
       compiler, `sus.run_program`, a REPL input -- renders the same way.
       They are *not* removed from argv: cli.funny strips them again on its
       side, and leaving them lets `funny --serious run x.funny` look the
       same to both halves. */
    DiagOptions diag = diag_default_options();
    bool wantVersion = false;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--serious") == 0) {
            diag.serious = true;
        } else if (strcmp(argv[i], "--no-color") == 0 || strcmp(argv[i], "--no-colour") == 0) {
            diag.color = false;
        } else if (strcmp(argv[i], "--version") == 0) {
            wantVersion = true;
        }
    }
    diag_set_default_options(diag);

    if (wantVersion) {
        printf("funny %s (bytecode v%d)\n", FUNNY_VERSION, FUNNY_BYTECODE_VERSION);
        return 0;
    }

    /* The toolchain is *in* this binary (native/toolchain_blob.c, generated by
       tools/bin2c.funny from the linked bundle). Nothing to find, nothing to
       ship alongside, nothing to get out of step with the executable. */
    size_t cliLen = toolchain_blob_len;
    const uint8_t *cliBytes = toolchain_blob;
    uint8_t *owned = load_cli_override(&cliLen);
    if (owned != NULL) cliBytes = owned;

    RunnerOptions opts = {diag, NULL};
    int status = funny_run_bytecode(cliBytes, cliLen, argv + 1, argc - 1, opts, NULL);
    free(owned);
    return status;
}
