/* native/main.c -- NATIVE_PLAN.md N8 task 6 + N10 task 1: the loader.
 *
 * Everything a user types is parsed and dispatched by selfhost/cli.funny,
 * which is FunnyLang. This file does the three things that cannot be done
 * from inside the language before the language is running:
 *
 *   1. set up the console (UTF-8 + ANSI on Windows),
 *   2. read the two diagnostic flags, because they configure the *runtime's*
 *      own renderer and have to apply before any program runs,
 *   3. hand the embedded toolchain bundle argv.
 *
 * The bundle is compiled into this binary as a byte array
 * (native/toolchain_blob.c, generated by tools/bin2c.funny), so the shipped
 * artifact is one file: nothing to find, nothing to ship alongside, nothing
 * that can get out of step with the executable. FUNNY_CLI replaces it from a
 * file, which is the development loop.
 *
 * `--version` is answered here rather than in the bundle, deliberately: it is
 * the one command someone runs when an install looks broken, so it must not
 * depend on anything else working.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "diag.h"
#include "interns.h"
#include "status.h"
#include "platform.h"
#include "runner.h"
#include "sus.h"
#include "toolchain_blob.h"

/* The version lives in three places and they must be moved together:
   here, `selfhost/cli.funny` and `selfhost/vibe.funny`. A test used to read
   them and compare -- `tests/native/test_native_cli.py` -- but N11 removed
   every `.py` from the repository and the CI job that proves there are none,
   so nothing checks this any more. Three copies of a version string is
   exactly the kind of thing that drifts silently, and now it can. */
#define FUNNY_VERSION "2.1.0"
#define FUNNY_BYTECODE_VERSION 2

static uint8_t *read_file(const char *path, size_t *outLen) {
    unsigned char *data;
    size_t len;
    char errbuf[256];
    if (!platform_read_file(path, &data, &len, errbuf, sizeof(errbuf))) return NULL;
    *outLen = len;
    return (uint8_t *)data;
}

/* FUNNY_CLI replaces the embedded toolchain with one from a file. This is
   the iteration loop: edit selfhost/, relink the bundle, point at it, without
   regenerating the blob and recompiling C in between. Deliberately *not* a
   search of the filesystem -- a shipped binary's behaviour should not depend
   on what happens to be sitting next to it. */
static uint8_t *load_cli_override(size_t *outLen) {
    const char *override = getenv("FUNNY_CLI");
    if (override == NULL || override[0] == '\0') return NULL;
    uint8_t *data = read_file(override, outLen);
    if (data == NULL) {
        fprintf(stderr, "FUNNY_CLI is set to '%s', which couldn't be read.\n", override);
        exit(1);
    }
    return data;
}

/* --dump-on-stall N: a thread that does nothing but notice when nothing is
   happening. Every thread touches its status row at each wait point, so "no
   row has been touched in N seconds" is as close to "this program is stuck"
   as anything can get from outside it (RUNTIME_PLAN.md R9).
 *
 * It reports at most once per stall, and keeps running afterwards -- a
 * program that unsticks itself and hangs again deserves a second dump. */
static double g_stallSeconds = 0.0;

static void stall_watchdog(void *userdata) {
    (void)userdata;
    bool reported = false;
    for (;;) {
        platform_sleep_seconds(0.5);
        double quiet = status_quiet_seconds();
        if (quiet >= g_stallSeconds) {
            if (!reported) {
                fprintf(stderr, "\nnothing has moved for %.0fs. here is what everybody is waiting on:\n", quiet);
                status_dump(stderr);
                reported = true;
            }
        } else {
            reported = false;
        }
    }
}

int main(int argc, char **argv) {
    platform_console_init(); /* UTF-8 + ANSI on Windows; a no-op elsewhere */

    /* The two flags that configure the runtime's own diagnostic renderer are
       read here and installed process-wide, so every nested run -- the
       compiler, `sus.run_program`, a REPL input -- renders the same way.
       They are *not* removed from argv: cli.funny strips them again on its
       side, and leaving them lets `funny --serious run x.funny` look the
       same to both halves. */
    DiagOptions diag = diag_default_options();
    bool wantVersion = false;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--serious") == 0) {
            diag.serious = true;
        } else if (strcmp(argv[i], "--no-color") == 0 || strcmp(argv[i], "--no-colour") == 0) {
            diag.color = false;
        } else if (strcmp(argv[i], "--dump-on-stall") == 0 && i + 1 < argc) {
            g_stallSeconds = strtod(argv[i + 1], NULL);
            if (g_stallSeconds < 1.0) g_stallSeconds = 1.0;
        } else if (strcmp(argv[i], "--version") == 0) {
            wantVersion = true;
        }
    }
    diag_set_default_options(diag);

    /* A hang is not something you get to prepare for in advance, so the
       dump is always available: SIGQUIT (Ctrl-\) on POSIX, Ctrl-Break on
       Windows. The watchdog only exists if it was asked for. */
    platform_on_dump_request(status_dump_raw);
    if (g_stallSeconds > 0.0) {
        PlatformThread watchdog;
        char watchdogErr[256];
        platform_thread_start(&watchdog, stall_watchdog, NULL, watchdogErr, sizeof watchdogErr);
    }

    if (wantVersion) {
        printf("funny %s (bytecode v%d)\n", FUNNY_VERSION, FUNNY_BYTECODE_VERSION);
        return 0;
    }

    /* The toolchain is *in* this binary (native/toolchain_blob.c, generated by
       tools/bin2c.funny from the linked bundle). Nothing to find, nothing to
       ship alongside, nothing to get out of step with the executable. */
    size_t cliLen = toolchain_blob_len;
    const uint8_t *cliBytes = toolchain_blob;
    uint8_t *owned = load_cli_override(&cliLen);
    if (owned != NULL) cliBytes = owned;

    /* Hand the same bytes to the runtime, so `sus.toolchain()` can return
       them: that is what lets a `.funny` test drive the command line through
       sus.run_bytecode instead of spawning a process, which the language has
       no way to do and should not grow a way to do just for its own tests.
       Registered rather than referenced from sus.c, because stub_main.c links
       neither this file nor toolchain_blob.c -- a yeeted executable carries a
       program and no compiler, and `sus.toolchain()` is `ghost` there. */
    sus_set_toolchain(cliBytes, cliLen);

    /* No script path: this run is the toolchain itself, which finds the
       user's program from argv and passes *its* path down to sus.run_program. */
    /* --dump-on-stall belongs to this binary alone: the toolchain has never
       heard of it and would take it for a filename. --serious and --no-color
       stay in, because cli.funny strips those on its own side and a nested
       run is meant to see them. */
    char **passArgv = (char **)malloc((size_t)(argc > 0 ? argc : 1) * sizeof(char *));
    int passArgc = 0;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--dump-on-stall") == 0 && i + 1 < argc) {
            i++;
            continue;
        }
        passArgv[passArgc++] = argv[i];
    }

    RunnerOptions opts = {diag, NULL, NULL, NULL, NULL};
    int status = funny_run_bytecode(cliBytes, cliLen, passArgv, passArgc, opts, NULL);
    free(passArgv);
    free(owned);
    /* Interns are joined as each VM is destroyed; this is the last sweep --
       the compiled-worker cache, and the registry itself. Nothing is killed:
       ASYNC_PLAN.md §3.4 -- a thread stopped mid-allocation leaves a heap
       nothing can safely free, so `funny` waits for its workers. */
    interns_shutdown();
    return status;
}
