/* native/opcodes.h -- PLAN.md §5.1, FROZEN. Mirrors funnylang/opcodes.py's
 * Op IntEnum exactly, numeric value for numeric value. Never renumber.
 */
#ifndef FUNNY_OPCODES_H
#define FUNNY_OPCODES_H

typedef enum {
    OP_NOP = 0,
    OP_CONST = 1,
    OP_GHOST = 2,
    OP_FAX = 3,
    OP_CAP = 4,
    OP_POP = 5,
    OP_DUP = 6,
    OP_SWAP = 7,
    OP_GET_LOCAL = 8,
    OP_SET_LOCAL = 9,
    OP_GET_GLOBAL = 10,
    OP_SET_GLOBAL = 11,
    OP_DEF_GLOBAL = 12,
    OP_GET_UPVAL = 13,
    OP_SET_UPVAL = 14,
    OP_CLOSE_UPVAL = 15,
    OP_GET_PROP = 16,
    OP_SET_PROP = 17,
    OP_GET_PROP_SAFE = 18,
    OP_GET_INDEX = 19,
    OP_SET_INDEX = 20,
    OP_GET_SLICE = 21,
    OP_ADD = 22,
    OP_SUB = 23,
    OP_MUL = 24,
    OP_DIV = 25,
    OP_IDIV = 26,
    OP_MOD = 27,
    OP_POW = 28,
    OP_NEG = 29,
    OP_NOT = 30,
    OP_BNOT = 31,
    OP_BAND = 32,
    OP_BOR = 33,
    OP_BXOR = 34,
    OP_SHL = 35,
    OP_SHR = 36,
    OP_EQ = 37,
    OP_NEQ = 38,
    OP_LT = 39,
    OP_LE = 40,
    OP_GT = 41,
    OP_GE = 42,
    OP_IN = 43,
    OP_JUMP = 44,
    OP_JUMP_IF_FALSE = 45,
    OP_JUMP_IF_TRUE = 46,
    OP_JUMP_IF_FALSE_KEEP = 47,
    OP_JUMP_IF_TRUE_KEEP = 48,
    OP_JUMP_IF_GHOST_KEEP = 49,
    OP_LOOP = 50,
    OP_CALL = 51,
    OP_INVOKE = 52,
    OP_INVOKE_OG = 53,
    OP_CLOSURE = 54,
    OP_RETURN = 55,
    OP_BUILD_STASH = 56,
    OP_BUILD_GROUPCHAT = 57,
    OP_BUILD_STRING = 58,
    OP_YAP = 59,
    OP_CHUCK = 60,
    OP_TRY_PUSH = 61,
    OP_TRY_POP = 62,
    OP_SQUAD = 63,
    OP_METHOD = 64,
    OP_INHERIT = 65,
    OP_IMPORT = 66,
    OP_EXPORT = 67,
    OP_ITER_NEW = 68,
    OP_ITER_NEXT = 69,
    OP_HALT = 70,
    OP_JUMP_LONG = 71,
    OP_LOOP_LONG = 72,
    OP_PTR_LOCAL = 73,
    OP_PTR_GLOBAL = 74,
    OP_PTR_UPVAL = 75,
    OP_PTR_INDEX = 76,
    OP_PTR_PROP = 77,
    OP_DEREF = 78,
    OP_SET_DEREF = 79,
} Op;

#endif /* FUNNY_OPCODES_H */
