/* GENERATED by tools/bin2c.funny -- do not hand-edit.
 * The declaration for toolchain_blob.c, whose bytes are bootstrap/cli.funnypak. */
#ifndef FUNNY_TOOLCHAIN_BLOB_H
#define FUNNY_TOOLCHAIN_BLOB_H

extern const unsigned char toolchain_blob[];
extern const unsigned int toolchain_blob_len;

#endif /* FUNNY_TOOLCHAIN_BLOB_H */
