/* native/unicode_tbl.h -- NATIVE_PLAN.md N11 task 3: Unicode character
 * classification and simple case mapping.
 *
 * `native/unicode_tbl.c` is GENERATED by `tools/gen_unicode.funny` (in
 * FunnyLang, run by `funny` -- N11 leaves no `.py` anywhere) and checked in,
 * so a build still needs nothing but a C compiler. Do not hand-edit it.
 *
 * WHY THIS EXISTS. `native/yapper.h` carries an AGENT CHOICE from N4 saying
 * that letter/alnum classification and case conversion are ASCII-only,
 * because the category tables did not exist yet. They were deferred to N5 and
 * then never written. The visible consequences: `yapper.is_letter("中")`
 * answered `cap` where the reference answers `fax`, and `yo 変数 = 1` was a
 * `LexerSaidNah` -- the lexer's identifier rule goes through `is_letter`.
 * Nothing in the 1,313-test pytest suite caught either, because that suite
 * runs the *Python* implementation.
 *
 * WHAT IS AND IS NOT COVERED. `unicode_is_letter` is general category L*,
 * which is exactly what Python's `str.isalpha()` accepts; `unicode_is_alnum`
 * adds Nd, Nl and No, which is exactly `str.isalnum()`. Case mapping is the
 * *simple* one-code-point-to-one-code-point mapping from UnicodeData.txt.
 * Full case mapping (SpecialCasing.txt, where `ß` uppercases to `SS`) is
 * deliberately absent: it cannot be a code-point map, nothing in the corpus
 * needs it, and a partial version that quietly differs from the reference
 * would be worse than a documented gap.
 *
 * SHAPE. Sorted, non-overlapping ranges, binary-searched. A flat
 * 0x110000-entry table would be 1.1 MB against a 2 MB binary ceiling;
 * Unicode assigns categories in blocks, so ranges hold the same information
 * in a few thousand entries.
 */
#ifndef FUNNY_UNICODE_TBL_H
#define FUNNY_UNICODE_TBL_H

#include <stdbool.h>
#include <stdint.h>

typedef struct {
    uint32_t start;
    uint32_t end; /* inclusive */
} UnicodeRange;

/* Every code point in [start, end] maps to itself plus `delta`. */
typedef struct {
    uint32_t start;
    uint32_t end; /* inclusive */
    int32_t delta;
} UnicodeCaseRun;

extern const UnicodeRange unicode_letter_ranges[];
extern const unsigned int unicode_letter_ranges_count;
extern const UnicodeRange unicode_numeric_ranges[];
extern const unsigned int unicode_numeric_ranges_count;
extern const UnicodeCaseRun unicode_upper_runs[];
extern const unsigned int unicode_upper_runs_count;
extern const UnicodeCaseRun unicode_lower_runs[];
extern const unsigned int unicode_lower_runs_count;

/* General category L* -- Python's str.isalpha() for a single character. */
bool unicode_is_letter(uint32_t cp);

/* L* plus Nd/Nl/No -- Python's str.isalnum() for a single character. */
bool unicode_is_alnum(uint32_t cp);

/* Simple case mapping; returns `cp` unchanged when there is none. */
uint32_t unicode_to_upper(uint32_t cp);
uint32_t unicode_to_lower(uint32_t cp);

#endif /* FUNNY_UNICODE_TBL_H */
