/* native/unicode.c -- the lookups over the generated tables.
 *
 * Hand-written, and deliberately a separate file from `unicode_tbl.c`: that
 * one is generated by `tools/gen_unicode.funny` and gets overwritten whole,
 * so nothing anybody wrote by hand may live in it. This is the only code
 * that reads those arrays.
 *
 * Everything here is a binary search over sorted, non-overlapping ranges.
 * The tables are built that way by construction -- UnicodeData.txt is in code
 * point order and the generator only ever extends the range it is currently
 * building -- so no sort or validation is needed at run time.
 */
#include "unicode_tbl.h"

#include <stddef.h>

static bool in_ranges(const UnicodeRange *ranges, unsigned int count, uint32_t cp) {
    unsigned int lo = 0, hi = count;
    while (lo < hi) {
        unsigned int mid = lo + (hi - lo) / 2;
        if (cp < ranges[mid].start) {
            hi = mid;
        } else if (cp > ranges[mid].end) {
            lo = mid + 1;
        } else {
            return true;
        }
    }
    return false;
}

static uint32_t apply_runs(const UnicodeCaseRun *runs, unsigned int count, uint32_t cp) {
    unsigned int lo = 0, hi = count;
    while (lo < hi) {
        unsigned int mid = lo + (hi - lo) / 2;
        if (cp < runs[mid].start) {
            hi = mid;
        } else if (cp > runs[mid].end) {
            lo = mid + 1;
        } else {
            /* int64 in the middle so a negative delta on a small code point
               cannot wrap through unsigned arithmetic on the way. */
            return (uint32_t)((int64_t)cp + runs[mid].delta);
        }
    }
    return cp;
}

bool unicode_is_letter(uint32_t cp) {
    return in_ranges(unicode_letter_ranges, unicode_letter_ranges_count, cp);
}

bool unicode_is_alnum(uint32_t cp) {
    return in_ranges(unicode_letter_ranges, unicode_letter_ranges_count, cp) ||
           in_ranges(unicode_numeric_ranges, unicode_numeric_ranges_count, cp);
}

uint32_t unicode_to_upper(uint32_t cp) {
    return apply_runs(unicode_upper_runs, unicode_upper_runs_count, cp);
}

uint32_t unicode_to_lower(uint32_t cp) {
    return apply_runs(unicode_lower_runs, unicode_lower_runs_count, cp);
}
