/* native/yapper.h -- funnylang/stdlib/yapper.py: string utilities
 * (`gimme yapper`) plus the yapstring instance-method table (bound via
 * GET_PROP/INVOKE for a bare yapstring receiver, e.g. `"hi".SCREAM()`).
 * Every function here treats `a[0]` as "the string" uniformly, whether
 * it's called as a module function (`yapper.split(s, ",")`, no implicit
 * receiver -- `a[0]` is just the first explicit argument) or as an
 * instance method (`s.split(",")`, `a[0]` is the bound receiver) --
 * exactly matching how funnylang/stdlib/yapper.py's own Python functions
 * are shared, unchanged, between `build()`'s `members` dict and its
 * separate `YAPSTRING_METHODS` dict. So this file registers each
 * function once and reuses the same NativeMethodFn in both tables,
 * rather than writing two wrappers per operation.
 *
 * RESOLVED in N11 task 3, and left here because the shape of the gap is
 * worth remembering: case conversion (SCREAM/whisper/title_case/
 * sarcasm_case) and letter/alnum classification (is_letter/is_alnum) used
 * to be ASCII-only, because the Unicode category tables were deferred from
 * N4 and then never written. Non-ASCII bytes passed through unchanged for
 * case conversion and counted as "not a letter" for classification, so
 * `yapper.is_letter("中")` answered `cap` and `yo 変数 = 1` did not lex --
 * the lexer's identifier rule goes through is_letter. Nothing in the
 * 1,313-test pytest suite noticed, because that suite runs the *Python*
 * implementation.
 *
 * These now go through `unicode_tbl.h`, whose tables are generated by
 * `tools/gen_unicode.funny` and checked in. One narrower gap remains and is
 * deliberate: only the *simple* (one-code-point-to-one) case mapping is
 * represented, not SpecialCasing.txt's full mapping where `ß` uppercases to
 * `SS`. Nothing in the corpus needs it and a partial version that quietly
 * differs from the reference would be worse than a stated absence.
 *
 * AGENT CHOICE: `format` supports only positional `{}`/`{N}` placeholders
 * (each filled in via to_display) -- not named fields or format specs
 * (`{:.2f}`), which would need reimplementing a real chunk of Python's
 * own format mini-language for one function, disproportionate to the
 * rest of this module.
 */
#ifndef FUNNY_YAPPER_H
#define FUNNY_YAPPER_H

#include "value.h"
#include "vm.h"

struct VM;

Value yapper_build(struct VM *vm);
NativeMethodFn yapstring_find_method(const char *name, int *outMinArity, int *outMaxArity);

#endif /* FUNNY_YAPPER_H */
